config/routes.rb
Rails.application.routes.draw do
  resources :stories do
    collection do
      get 'my_stories' => 'stories#my_stories'
      get 'bookmarked_stories' => 'stories#bookmarked_stories'
      get 'liked_stories' => 'stories#liked_stories'

    end
    resource :like, only: [:create, :destroy]
    resource :bookmark, only: [:create, :destroy]
    resources :comments
  end

  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:show, :index, :user_stories] do
    member do
      post :follow
      delete :unfollow
    end

  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :story

  validates_presence_of :body
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_story, only: [:create, :index, :destroy]
  before_action :find_comment, only: [:destroy]


def index

end

  def create
   @comment = @story.comments.create(comment_params)
   @comment.user_id = current_user.id

   respond_to do |format|
     if @comment.save
       format.html { redirect_to @story, notice: 'Comment was successfully created.' }
       format.json { render :show, status: :created, template: 'stories/show' }
     else
       format.html { redirect_to @story, error: 'Comment has some error.' }
       format.json { render json: @comment.errors, status: :unprocessable_entity }
     end
   end
  end

def new

end

def show

end

def update

end

def destroy

  @comment.destroy
  redirect_to story_path(@story)
end

def edit

end




  private

  def set_story
    @story = Story.find(params[:story_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:body)
  end
  def find_comment
    @comment = @story.comments.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<% @comments.each do |comment| %>


<div class="panel panel-info">
  <div class="panel-heading">
    <%= link_to comment.user.name, user_path(comment.user) %>
  </div>
  <div class="panel-body">
    <p><%= comment.body %></p>

  </div>
  <div class="panel-footer text-right">
        <p><%= time_ago_in_words(comment.created_at)  %> ago
        <% if current_user == comment.user %>
        <%= link_to "Delete", [comment.story, comment], method: :delete, class: "btn btn-primary btn-sm"  %>
        <%end%>
        </p>
  </div>
</div>



<% end %>

<%= render 'comments/form' %>

app/views/comments/_form.html.erb
<%= simple_form_for([@story, @story.comments.build]) do |f| %>


<div class="col-lg-6 col-lg-offset-3">
  <div class="input-group">
    <%= f.text_area :body, class: "form-control", type: "text", placeholder: "Add your comment" %>
    <span class="input-group-btn">
       <%= f.button :submit, class: "btn btn-primary" %>
    </span>
  </div>
    <br><br><br><br><br><br><br><br>
    <!-- #<%= link_to "Add Comment", new_story_comment_path(@story), class: "btn btn-primary btn-lg" %> -->
<% end %>