config/routes.rb
Rails.application.routes.draw do
  resources :stories do
    collection do
      get 'my_stories' => 'stories#my_stories'
      get 'bookmarked_stories' => 'stories#bookmarked_stories'
      get 'liked_stories' => 'stories#liked_stories'

    end
    resource :like, only: [:create, :destroy]
    resource :bookmark, only: [:create, :destroy]
    resources :comments
  end

  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:show, :index, :user_stories] do
    member do
      post :follow
      delete :unfollow
    end

  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

         has_many :stories, dependent: :destroy
         has_many :likes, dependent: :destroy
         has_many :bookmarks, dependent: :destroy
         has_many :comments, dependent: :destroy

         has_many :following_followships, class_name: 'Followship', foreign_key: 'follower_id', dependent: :destroy
         has_many :followings, through: :following_followships, dependent: :destroy

         has_many :follower_followships, class_name: 'Followship', foreign_key: 'following_id', dependent: :destroy
         has_many :followers, through: :follower_followships, dependent: :destroy


         def likes?(story)
           story.likes.where(user_id: id).any?
         end
         def bookmarks?(story)
           story.bookmarks.where(user_id: id).any?
         end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :follow, :unfollow, :user_stories]


  def index
    @users = User.where.not(id: current_user.id).all
  end




  def show
      respond_to do |format|
        format.html { render template: "users/user"}
        format.json { render template: "users/user", status: :ok }
      end
  end
  # def show
  #   @stories = @user.stories.all
  # end

  def follow
    if current_user != @user
      current_user.following_followships.first_or_create(following: @user)
      respond_to do |format|
        format.html { redirect_to :back, notice: "Followship created." }
        format.json { render json: {errors: ["User cannot follow himself"]}, status: :unprocessable_entity }
      end
    else
      respond_to do |format|
        format.html { redirect_to :back }
        format.json { render json: {errors: ["User cannot follow himself"]}, status: :unprocessable_entity }
      end
    end
  end

  def unfollow
    if current_user != @user
      Followship.find_by(follower: current_user, following: @user).destroy
      respond_to do |format|
        format.html { redirect_to :back, notice: "Followship removed." }
        format.json { render json: {errors: ["User cannot follow himself"]}, status: :unprocessable_entity }
      end
    else
      respond_to do |format|
        format.html { redirect_to :back }
        format.json { render json: {errors: ["User cannot follow himself"]}, status: :unprocessable_entity }
      end
    end
  end

  private


  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container">
  <div class="row">


        <h1 class="text-center">Our Writers <small>and their story counts</small></h1>


        <% @users.each do |user| %>
        <div class="col-md-8 col-md-offset-2">
          <ul class="list-group">
            <li class="list-group-item justify-content-between"><strong><%= link_to user.name, user_path(user.id) %></strong><span class="badge badge-default badge-pill"><%=user.stories.count%></span>
              <% if current_user.following_followships.find_by(following: user).nil? %>
                <%= link_to "Follow", follow_user_path(user), class: "btn btn-primary btn-sm", method: :post %>
                <% else %>
                <%= link_to "Unfollow", unfollow_user_path(user), class: "btn btn-primary btn-sm", method: :delete %>
                <% end %>
            </li>
          </ul>
        </div>


        <%end%>

  </div>

</div>

app/views/users/user.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center"><%= @user.name %><small> our talented writer</small></h1>
    <h3 class="text-center"><%= @user.email%></h3>
    <div class="col-md-4 col-md-offset-5">
        <% if current_user != @user %>
        <% if current_user.following_followships.find_by(following: @user).nil? %>
          <%= link_to "Follow #{@user.name}", follow_user_path, class: "btn btn-primary btn-lg", method: :post %>
          <% else %>
          <%= link_to "UnFollow #{@user.name}", unfollow_user_path, class: "btn btn-primary btn-lg", method: :delete %>
          <% end %>
        <%else%>
        <%= link_to "Edit My Profile", edit_user_registration_path, class: "btn btn-primary btn-lg" %>
        <%end%>
    </div><br><br><br>

    <% @user.stories.each do |story|%>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title"><em><%= story.title %></em><small class="pull-right" style="color:#fff"><b> by <%= link_to story.user.name, user_path(story.user.id) %></small></b></h3>
      </div>
      <div class="panel-body">
        <p><%= story.body.truncate_words(15) %><em>...(Click Show to read complete story)</em></p>
      </div>
      <div class="panel-footer">

          <%= link_to 'Show', story, class: "btn btn-info" %>
          <% if current_user == story.user%>
          <%= link_to 'Edit', edit_story_path(story), class: "btn btn-info" %>
          <%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %>
          <%end%>
          <p class="pull-right"><%= time_ago_in_words(story.created_at)  %> ago </p>
      </div>
    </div>
      <%end%>


  </div>
</div>