config/routes.rb
Rails.application.routes.draw do
  resources :stories do
    collection do
      get 'my_stories' => 'stories#my_stories'
      get 'bookmarked_stories' => 'stories#bookmarked_stories'
      get 'liked_stories' => 'stories#liked_stories'

    end
    resource :like, only: [:create, :destroy]
    resource :bookmark, only: [:create, :destroy]
    resources :comments
  end

  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:show, :index, :user_stories] do
    member do
      post :follow
      delete :unfollow
    end

  end

end

app/models/story.rb
class Story < ActiveRecord::Base
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :bookmarks, dependent: :destroy
    has_many :comments, dependent: :destroy

    validates_presence_of :title, :body
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :authenticate_user! #, except: [:index, :show]
  before_action :set_story, only: [:show, :edit, :update, :destroy]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all.order(created_at: :desc)
  end

  def my_stories
    @my_stories = current_user.stories.all.order(created_at: :desc)

    respond_to do |format|
      format.html { render template: "stories/my_stories"}
      format.json { render template: "stories/index", status: :ok  }
    end
  end
  def bookmarked_stories
    #has many through relationship krni he lazmi!!!!!!
    @stories = []
    current_user.bookmarks.each do |bookmark|
      @stories.push(bookmark.story)
    end

    respond_to do |format|
      format.html { render template: "stories/bookmarked_stories"}
      format.json { render template: "stories/index", status: :ok  }
    end
  end

  def liked_stories
    #has many through relationship krni he lazmi!!!!!!
    @stories = []
    current_user.likes.each do |like|
      @stories.push(like.story)
    end
    respond_to do |format|
      format.html { render template: "stories/liked_stories"}
      format.json { render template: "stories/index", status: :ok  }
    end
  end
  # GET /stories/1
  # GET /stories/1.json
  def show
    @comments = Comment.where(story_id: @story).order("created_at DESC")
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
    authorize! :manage, @story
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)
    @story.user = current_user

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    authorize! :manage, @story
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    authorize! :manage, @story
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:title, :body)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_bookmarks.html.erb
<% if current_user && current_user.bookmarks.where(story_id: @story.id).count > 0 %>
<%= link_to "Remove Bookmark", story_bookmark_path(@story), method: :delete, class: "btn btn-warning"%>
<%else%>
<%= link_to "Add Bookmark", story_bookmark_path(@story), method: :post, class: "btn btn-success"%>
<%end%>

app/views/stories/_form.html.erb
<div class="container">
  <div class="row">
      <%= simple_form_for(@story, class: "form-horizontal") do |f| %>
      <%= f.error_notification %>

      <div class="jumbotron">
        <div class="container col-md-4 col-md-offset-4">
            <%= f.input :title, label: false, placeholder: "Title:", class: "form-control" %>
        </div>

            <%= f.text_area :body, label: false, placeholder: "Your epic story", class: "form-control", rows: 15 %>
      </div>

      <div class="form-group">
        <%= f.button :submit, class: "btn btn-primary" %>
      </div>
    <% end %>

  </div>
</div>

app/views/stories/_likes.html.erb
<% if current_user && current_user.likes.where(story_id: @story.id).count > 0 %>
<%= link_to "Unlike", story_like_path(@story), method: :delete, class: "btn btn-success"%>
<%else%>
<%= link_to "Like", story_like_path(@story), method: :post, class: "btn btn-success"%>
<%end%>

app/views/stories/bookmarked_stories.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center"><b> Your Bookmarks</b> <small>to continue your reading</small></h1>

<% @stories.each do |story|%>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><em><%= story.title %></em><small class="pull-right" style="color:#fff"><b> by <%= story.user.name %></small></b></h3>
  </div>
  <div class="panel-body">
    <%= story.body %>
  </div>
  <div class="panel-footer">
      <%= link_to 'Show', story, class: "btn btn-info" %>
      <% if current_user == story.user%>
      <%= link_to 'Edit', edit_story_path(story), class: "btn btn-info" %>
      <%= link_to 'Delete', story, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %>
      <%end%>

      <p class="pull-right"><%= time_ago_in_words(story.created_at)  %> ago </p>
  </div>
</div>
  <%end%>




<%= link_to 'New Story', new_story_path, class: "btn btn-primary" %>

app/views/stories/edit.html.erb
<h1 class="text-center">Edit your Story</h1>

<%= render 'form' %>

<%= link_to 'Back to Stories', stories_path, class: "btn btn-primary" %>
<%= link_to 'Show', @story, class: "btn btn-primary" %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">


<div class="row">
<h1 class="text-center"><b>Stories</b> <small>by our wonderful writers</small></h1>
<%= link_to 'New Story', new_story_path, class: "btn btn-primary pull-right" %>

</div>
</div>
<br>
<% @stories.each do |story|%>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><em><%= story.title %></em><small class="pull-right" style="color:#fff"><b> by <%= link_to story.user.name, user_path(story.user.id), style: "color: white;" %></small></b></h3>
  </div>
  <div class="panel-body">
    <p><%= story.body.truncate_words(15) %><em>...(Click Show to read complete story)</em></p>
  </div>
  <div class="panel-footer">

      <%= link_to 'Show', story, class: "btn btn-info" %>
      <% if current_user == story.user%>
      <%= link_to 'Edit', edit_story_path(story), class: "btn btn-info" %>
      <%= link_to 'Delete', story, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %>
      <%end%>
      <p class="pull-right"><%= time_ago_in_words(story.created_at)  %> ago </p>
  </div>
</div>
  <%end%>






<br><br>

app/views/stories/liked_stories.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center"><b> All Stories</b> <small>that you loved</small></h1>

<% @stories.each do |story|%>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><em><%= story.title %></em><small class="pull-right" style="color:#fff"><b> by <%= story.user.name %></small></b></h3>
  </div>
  <div class="panel-body">
    <%= story.body %>
  </div>
  <div class="panel-footer">
      <%= link_to 'Show', story, class: "btn btn-info" %>
      <% if current_user == story.user%>
      <%= link_to 'Edit', edit_story_path(story), class: "btn btn-info" %>
      <%= link_to 'Delete', story, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %>
      <%end%>

      <p class="pull-right"><%= time_ago_in_words(story.created_at)  %> ago </p>
  </div>
</div>
  <%end%>




<%= link_to 'New Story', new_story_path, class: "btn btn-primary" %>

app/views/stories/my_stories.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center"><b> All Stories</b> <small>by your wishful hands</small></h1>

<% @my_stories.each do |story|%>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title"><em><%= story.title %></em><small class="pull-right" style="color:#fff"><b> by <%= story.user.name %></small></b></h3>
  </div>
  <div class="panel-body">
    <%= story.body %>
  </div>
  <div class="panel-footer">
      <%= link_to 'Show', story, class: "btn btn-info" %>
      <%= link_to 'Edit', edit_story_path(story), class: "btn btn-info" %>
      <%= link_to 'Delete', story, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %>
      <p class="pull-right"><%= time_ago_in_words(story.created_at)  %> ago </p>
  </div>
</div>
  <%end%>




<%= link_to 'New Story', new_story_path, class: "btn btn-primary" %>

app/views/stories/new.html.erb
<div class="container">
<div class="row">


<h1 class="text-center">A new story<small> by <%= current_user.name%></small></h1>





<%= render 'form' %><br>

<%= link_to 'Back', stories_path, class: "btn btn-primary" %>
</div>
</div>

app/views/stories/show.html.erb
<div class="container">
  <div class="row">
    <h1 class="text-center">A masterpiece <small>by <%= @story.user.name %></small></h1>

    <div class="jumbotron">

    <p id="notice"><%= notice %></p>

    <p>
      <h2 class="text-center"><strong><em><%= @story.title %></em><strong></h2>

    </p><br>

    <p class="text-justify">

      <%= @story.body %>
    </p>

   </div>


   <div class="container">
     <div class="row">

       <p><%= render partial: "likes" %><%=@story.likes.count%></p>
       <p><%= render partial: "bookmarks" %>
       <% if current_user == @story.user%>
       <%= link_to 'Edit', edit_story_path(@story), class: "btn btn-primary" %>
       <%end%>
       <%= link_to 'Back', stories_path, class: "btn btn-primary" %>
     </div>
   </div>

    <%= render "comments/comment" %>



  </div>
</div>