config/routes.rb
Rails.application.routes.draw do
  resources :stories do
    collection do
      get 'my_stories' => 'stories#my_stories'
      get 'bookmarked_stories' => 'stories#bookmarked_stories'
      get 'liked_stories' => 'stories#liked_stories'

    end
    resource :like, only: [:create, :destroy]
    resource :bookmark, only: [:create, :destroy]
    resources :comments
  end

  root to: 'pages#home'
  devise_for :users
  resources :users, only: [:show, :index, :user_stories] do
    member do
      post :follow
      delete :unfollow
    end

  end

end

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MyMedium", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Write a Story", new_story_path %></li>
        <li><%= link_to "Stories", stories_path%></li>
        <li><%= link_to "Writers", users_path %></li>
        <% unless current_user %>
        <li><%= link_to "Sign in/ Sign up", new_user_session_path %></li>
        <%end%>
        <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li><%= link_to "My Stories", my_stories_stories_path %></li>
              <li><%= link_to "My Bookmarks", bookmarked_stories_stories_path %></li>
              <li><%= link_to "Liked Stories", liked_stories_stories_path %></li>
              <li role="separator" class="divider"></li>
              <li> <%=link_to "My Profile", user_path(current_user) %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>


        <%end%>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyMedium</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="row">
    <%= render "layouts/header" %>

    

<%= yield %>
</div>
</div>
</body>
</html>